### ISSUE TITLE
Archive the project?

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/espmonitor#153]
@kelnos, thanks again for your hard work on this project! I believe that most (all?) of the functionality of this crate has been implemented in espflash itself, under the `espflash monitor` command. What are your thoughts on deprecating and archiving this project?

**Comment by kelnos** [comment]
Yeah, it's probably fine to archive it.  As I'm sure is obvious, I haven't had much time for this in a long while, and if `espflash` has it all, no need for the redundancy.
