### ISSUE TITLE
Keypresses cause output to halt

### ISSUE THREAD

**Issue by tcbennun** [esp-rs/espmonitor#2]
I find that any keypress input while monitoring causes serial data to stop arriving into stdout. This includes CTRL+R, in which case I see `Resetting device... done` immediately before it stops.

My system:

- Distro: Debian testing
- Kernel: 5.10.46

My device: ESP32-PICO-D4, using USB serial chip CH340.

v0.4.0 works fine. The first bad commit is 0ab7587780c7, where the loops within `handle_stdin` and `handle_serial`.

This appears to be because `io::stdin().read()` blocks if no data is available, meaning the outermost `loop` in `handle_stdin` never stops.

The following patch fixes it for me (whitespace omitted, I'll post a PR).

```
diff --git a/espmonitor/src/lib.rs b/espmonitor/src/lib.rs
index a880711..a9c5ea1 100644
--- a/espmonitor/src/lib.rs
+++ b/espmonitor/src/lib.rs
@@ -274,7 +274,6 @@ fn reset_chip(dev: &mut SerialStream) -> io::Result<()> {
 
 fn handle_stdin(reader: &mut SerialReader) -> io::Result<()> {
     let mut buf = [0; 32];
-    loop {
     match io::stdin().read(&mut buf)? {
         bytes if bytes > 0 => {
             for b in buf[0..bytes].iter() {
@@ -284,9 +283,9 @@ fn handle_stdin(reader: &mut SerialReader) -> io::Result<()> {
                     _ => (),
                 }
             }
+            Ok(())
         },
-            _ => return Ok(()),
-        }
+        _ => Ok(()),
     }
 }
```

I see no issue with this - now we loop over however much data is available, before returning to polling.

**Comment by kelnos** [comment]
Fixed in 0.4.2
