### ISSUE TITLE
When run in workspace, an error occurs.

### ISSUE THREAD

**Issue by fuminori-hakoishi** [esp-rs/espmonitor#59]
When I run `cargo espmonitor` in workspace, I get an error and
If I `cd` to the flushed package directory and then run it, it works fine.

I want to run espmonitor by specifying the package from the workspace directory.

```powershell
> cargo espmonitor com4
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "missing field `package`", key: [] 
} }', C:\Users\<user name>\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-espmonitor-0.9.0\src\main.rs:141:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

> cd .\<sub package>\

<subpackage > cargo espmonitor com4
ESPMonitor 0.9.0

Commands:
    CTRL+R    Reset chip
    CTRL+C    Exit

Opening com4 with speed 115200
WARNING: Unable to open flash image \\?\C:\<workspace dir>\<subpackage>\target\xtensa-esp32-espidf\debug\<subpackage>: 指定されたパスが見つかりません。 (os error 3)
Resetting device... done
ets Jul 29 2019 12:21:46

~
~
~

It worked properly.

```

**Comment by kelnos** [comment]
I pushed a branch that I think will address this: https://github.com/esp-rs/espmonitor/pull/61

Is there any chance you can test it?  I don't have a multi-crate workspace for esp32 that I can use to test.  Should be able to install it easily with:
```
cargo install --git https://github.com/esp-rs/espmonitor --branch support-workspaces cargo-espmonitor
```

Without any extra arguments given, it should try to find the first bin crate in the `members` list and use that.  You can pass `--bin` or `--example` to have it search for a specific bin/example.

**Comment by kelnos** [comment]
(Note that cargo-espflash doesn't appear to have a `--bin` option, so I'm not 100% sure what will happen if you have multiple bin crates in the workspace and also pass `--flash`.)

**Comment by kelnos** [comment]
cc @ivmarkov not sure if cargo-espflash supports multi-crate workspaces.  I added some (somewhat messy) code to support them here in cargo-espmonitor, but people passing `--flash` might see different behavior from the flashing step.

**Comment by fuminori-hakoishi** [comment]
@kelnos 

Thanks. I was able to run espmonitor from workspaces successfully.

---

BTW, cargo-espflash gives me the following error when I run it in multi-crate workspaces.

```powershell
> cargo espflash       
Serial port: COM4
Connecting...
    Finished dev [optimized + debuginfo] target(s) in 0.41s
Error: cargo_espflash::multiple_artifacts

  × Failed to build project
  ╰─▶ Multiple build artifacts found
  help: Please specify which artifact to flash using --bin
```

But I didn't know how to use --bin, so I used --package and was able to flash one package with `cargo espflash <com> <package name>`.

**Comment by kelnos** [comment]
Oh, neat, I didn't see `--package`.  I'll set things up so if you pass `--bin` to `cargo espmonitor`, then it will pass it on to `cargo espflash` as `--package`.

**Comment by kelnos** [comment]
Ok, updated the PR to pass `--package` to espflash if needed.  So hopefully the two should work together.
